//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorldYachtsDesktopApp.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Boats
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Boats()
        {
            this.Fit = new HashSet<Fit>();
            this.Order = new HashSet<Order>();
        }
    
        public int BoatId { get; set; }
        public string Model { get; set; }
        public string BoatType { get; set; }
        public int NumberOfRowers { get; set; }
        public bool Mast { get; set; }
        public string Colour { get; set; }
        public string Wood { get; set; }
        public decimal BasePrice { get; set; }
        public string VAT { get; set; }
        public bool IsDeleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fit> Fit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Order { get; set; }
    }
}
