//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorldYachtsDesktopApp.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int UserId { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public int RoleId { get; set; }
        public System.DateTime LastInteractionDate { get; set; }
        public System.DateTime LastChangePasswordDate { get; set; }
        public bool IsDeleted { get; set; }
        public bool IsBlocked { get; set; }
    
        public virtual Role Role { get; set; }
    }
}
